/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatapp;

import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author egypt2
 */
public class chatFrame extends javax.swing.JFrame implements Runnable{

     JButton clientBtn;
     DatagramSocket socket;
     DatagramPacket packet;
     ArrayList<String> connectors = new ArrayList<String>();
     DefaultListModel model = new DefaultListModel();
     DefaultListModel chatModel = new DefaultListModel();
     
    /**
     * Creates new form chatFrame
     */
    public chatFrame() throws SocketException, IOException {
        initComponents();      
        socket = new DatagramSocket(8000);
        socket.setBroadcast(true);
    //  whoIsConnected();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        onlineList = new javax.swing.JList<String>();
        unicastChatBtn = new javax.swing.JButton();
        broadCastChatBtn = new javax.swing.JButton();
        addIpTxt = new javax.swing.JTextField();
        addIpBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JList<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ErrorMsg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));

        jScrollPane1.setViewportView(onlineList);

        unicastChatBtn.setText("Send Unicast");
        unicastChatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unicastChatBtnMouseClicked(evt);
            }
        });
        unicastChatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unicastChatBtnActionPerformed(evt);
            }
        });

        broadCastChatBtn.setText("Send Broadcast");
        broadCastChatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                broadCastChatBtnMouseClicked(evt);
            }
        });
        broadCastChatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                broadCastChatBtnActionPerformed(evt);
            }
        });

        addIpTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIpTxtActionPerformed(evt);
            }
        });

        addIpBtn.setText("Add ip");
        addIpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addIpBtnMouseClicked(evt);
            }
        });
        addIpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIpBtnActionPerformed(evt);
            }
        });

        message.setColumns(20);
        message.setRows(5);
        jScrollPane2.setViewportView(message);

        jScrollPane3.setViewportView(chatArea);

        jLabel1.setText("Exist Ips");

        jLabel2.setText("Message area");

        jLabel3.setText("chat area");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Messenger");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addIpTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(addIpBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(unicastChatBtn)
                                .addGap(46, 46, 46)
                                .addComponent(broadCastChatBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unicastChatBtn)
                    .addComponent(broadCastChatBtn)
                    .addComponent(addIpBtn)
                    .addComponent(addIpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void run()
    {
          while(true)
            {
           try {
                byte[] buff = new byte[2048];
                packet = new DatagramPacket(buff,buff.length);
                socket.receive(packet);
                System.out.println(new String(packet.getData(),0,packet.getData().length));
                chatModel.addElement(packet.getAddress().getHostAddress()+" ==> "+ new String(packet.getData(),0,packet.getData().length));
                chatArea.setModel(chatModel);
            } catch (IOException ex) {
                System.out.println(ex);
            }
        }

    }
    public void start()
    {
        Thread thread = new Thread(this);
        thread.start();
    }
    public void send(String message,String ip)
    {
            try {
                byte[] buffer = message.getBytes();
		
		DatagramPacket packet = new DatagramPacket(buffer, buffer.length);
		
                packet.setSocketAddress(new InetSocketAddress(ip, 8000));
		
		socket.send(packet);
            
       
                System.out.println("i have send"+ new String(packet.getData(),0,packet.getLength()));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Send Failed");
        }
    }
    private void unicastChatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unicastChatBtnMouseClicked
         try {
             
             if(!"".equals(message.getText()))
             {
                 
             int selectedIndex = onlineList.getSelectedIndex();
             String selectedIp = connectors.get(selectedIndex);
             send(message.getText(),selectedIp);
             chatModel.addElement(InetAddress.getLocalHost().getHostAddress()+"==> "+message.getText());
             chatArea.setModel(chatModel);
             message.setText("");
             
             ErrorMsg.setText("");

             }else
             {
                          ErrorMsg.setText("enter Your Message");

             }
             
         } catch (Exception ex) {
             ErrorMsg.setText("select friend IP that you want chat And enter Message");
             //Logger.getLogger(chatFrame.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_unicastChatBtnMouseClicked

    private void broadCastChatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_broadCastChatBtnMouseClicked
       String broadCastIp = "255.255.255.255";
       String messageTxt = message.getText();
       send(messageTxt,broadCastIp);
       message.setText("");
    }//GEN-LAST:event_broadCastChatBtnMouseClicked

    private void unicastChatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unicastChatBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unicastChatBtnActionPerformed

    private void addIpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addIpBtnMouseClicked
        
        String newIp = addIpTxt.getText();
        connectors.add(newIp);
        model.addElement(newIp);
        onlineList.setModel(model);
        addIpTxt.setText("");
    }//GEN-LAST:event_addIpBtnMouseClicked

    private void addIpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIpBtnActionPerformed

    private void addIpTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIpTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIpTxtActionPerformed

    private void broadCastChatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_broadCastChatBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_broadCastChatBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                System.out.println(" hello");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new chatFrame().setVisible(true);
                    
                } catch (IOException ex) {
                    Logger.getLogger(chatFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorMsg;
    private javax.swing.JButton addIpBtn;
    private javax.swing.JTextField addIpTxt;
    private javax.swing.JButton broadCastChatBtn;
    private javax.swing.JList<String> chatArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea message;
    private static javax.swing.JList<String> onlineList;
    private javax.swing.JButton unicastChatBtn;
    // End of variables declaration//GEN-END:variables
}
